services:
  backend:
    build: ./backend
    ports:
      - "4000:4000" 
    networks:
      - test
    environment:
      MONGO_URI: mongodb+srv://beasaini2002:IsTWuriDUj1BaAwQ@healthnfinity.cenia.mongodb.net/?retryWrites=true&w=majority&appName=Healthnfinity
      JWT_SECRET: Bc$2020064

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  
    networks:
      - test 

networks:
  test:
    driver: bridge